### PR TITLE
Allow to mark new mail as read

### PR DESCRIPTION
**Pull request by romanofski**
I'm currently using the attached patch to mark mails as read, but I have trouble running the tests. What is the procedure to successfully run all tests? I'll add a test for my patch and re-issue the pull request.

Cheers!

### CODE REVIEW

**Comment by romanofski** [comment]
Just in to elaborate in what I mean by "trouble running tests", here is what I get with different python versions:

```
$python3.3 ./run-testsuite
[...]
Ran 44 tests in 0.329s
FAILED (errors=43)

$python2.7 ./run-testsuite
[...]
Ran 44 tests in 1.679s
FAILED (failures=1, errors=22)
```

So perhaps I need additional dependencies?, sandbox configuration? or something else to run all existing tests successfully?

**Comment by jrosdahl** [comment]
> I have trouble running the tests.

Right, I also get a failing test with Python 3.3.2, so some behavior has changed since last time I run the tests. I've now pushed 45cbb3c which hopefully fixes the problem for you as well.

**Comment by romanofski** [comment]
Ok I got closer to the the issue with tests running for python2.7 almost without failures. I've looked into the Makefile and ran the `make maildirproc-python2`, which some of the tests are relying on.

Still, all tests with python 3.3 are failing with:

```
======================================================================
ERROR: test_utf8_header (__main__.Python3TestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run-testsuite", line 286, in test_utf8_header
    self.run_mdp(rc, ["incoming"])
  File "./run-testsuite", line 81, in run_mdp
    p.communicate(textwrap.dedent(rc))
  File "/home/rjoost/tools/python3.3/lib/python3.3/subprocess.py", line 903, in communicate
    self.stdin.write(input)
TypeError: 'str' does not support the buffer interface

----------------------------------------------------------------------
```

Just wondering, are they supposed to run under 3.3? If so I might need to dig deeper as to why they're failing for me.

Regarding your proposal: absolutely. The patch is currently a bit of a quickie ...

**Comment by jrosdahl** [comment]
> Still, all tests with python 3.3 are failing with:

Looks like you are running the testsuite with Python 3? That's not supported. However, the testsuite (when run with Python 2) tests both the Python 2 and the Python 3 version of maildirproc.

**Comment by romanofski** [comment]
Ah right. Cheers for clarifying. Why did I think it'll run on Python 3? Hm.. nevermind :)

**Comment by romanofski** [comment]
Ok, new pull request, this time with I think something worthwhile to merge. I would have added more documentation, but it seems you're keeping it not in the source tree. Let me know if anything in there needs changing.

Cheers for the useful app.

**Comment by jrosdahl** [comment]
Looks good.

> I would have added more documentation, but it seems you're keeping it not in the source tree.

Putting the documentation in the source tree sounds like a good idea! What would be a good location, perhaps a doc subdirectory? Oh, wait, it's already there?! ;-) Seriously, added docs for the new method would be welcome!

**Comment by jrosdahl** [comment]
Hi again,

Any progress on this one?

**Comment by romanofski** [comment]
I'm so sorry, but I totally lost track of this. Documentation: I've had a look around this time. Usually for Python projects we'd put the documentation in `doc` using [sphinx](http://sphinx-doc.org/). Yet I think that would be an entirely different commit. It will need setup code and more documentation of the remaining features.

You already have HTML documentation in doc, so perhaps I'll update `index.html` and update the pull request.

**Comment by romanofski** [comment]
Note: I haven't added the docs in `index.html`, but in `reference.html` which is more suited I think.

**Comment by jrosdahl** [comment]
> Usally for Python projects we'd put the documentation in doc using sphinx.

("We" does not include me in this case. :-) Also, maildirproc is much older than sphinx.)

> I haven't added the docs in index.html, but in reference.html which is more suited I think.

Yup.

**Comment by jgrassler** [comment]
Mark created a new pull request for the current mailprocessing code base here:  https://github.com/mailprocessing/mailprocessing/pull/10

Closing this one.

**Pull request closed without merging**
